"""set embedding dimension to 768

Revision ID: b662dc4751d4
Revises: bdd80dfd9e92
Create Date: 2026-09-15 06:04:06.793604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b662dc4751d4'
down_revision: Union[str, Sequence[str], None] = 'bdd80dfd9e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE faq_chunks ALTER COLUMN embedding TYPE vector(768);")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE faq_chunks ALTER COLUMN embedding TYPE vector;")
    # ### end Alembic commands ###
