"""add metadata to faq tables

Revision ID: bdd80dfd9e92
Revises: 0c38a0913dc2
Create Date: 2026-09-15 05:44:51.587161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdd80dfd9e92'
down_revision: Union[str, Sequence[str], None] = '0c38a0913dc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faq_chunks', sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('faq_documents', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faq_documents', 'source')
    op.drop_column('faq_chunks', 'chunk_metadata')
    # ### end Alembic commands ###
